### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by KishanVishwakarma-Official** [grantgasser/Alzheimers-Prediction#1]
hello sir,

please guide me to download this dataset 

thanks and regards
Kishan Vishwakarma
kishanv10090@gmail.com

**Comment by aditya-trivedi** [comment]
Create an account on https://ida.loni.usc.edu
Then Once the account is approved ,
Go ahead and login.
After Login Go to the Download Section - >  Study Data -> Test Data (In Sidenav) -> Challenges 
There You'll see the data .

**Comment by sinhprous** [comment]
Hi @KishanVishwakarma-Official , could you please send your data to my email: sinhprous@gmail.com 
Thanks in advance!

**Comment by AfiyaParveen** [comment]
Hi @KishanVishwakarma-Official , could you please share the ADNI preprocessed datasets as i'm facing some problems while downloading. please help me by sharing the ADNI datasets through google drive if not preprocessed, original is also helpful. my email id parveen7afiya@gmail.com
Thanks,
Parveen

**Comment by JVB25** [comment]
hello @sinhprous @KishanVishwakarma-Official @grantgasser @AfiyaParveen @aditya-trivedi if any of you has the data set can you please mail it to janhavibudihal@gmail.com 
Thank you

**Comment by grantgasser** [comment]
Hi all! I appreciate the interest in this repo and dataset. I'm quite surprised at the attention its gotten. This was my first ever data science project in school and leaves much to be desired in terms of quality and analysis (for example using accuracy as a metric rather than something more robust like AUC or F1 score).

That said, predicting Alzheimer's is a super cool and important task and I encourage all of you to make an attempt with this data - even submit a PR if you're up for it!

Unfortunately, per the [Data Use Agreement](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://adni.loni.usc.edu/wp-content/uploads/how_to_apply/ADNI_Data_Use_Agreement.pdf), "redistribution of data in any manner is prohibited." But you can apply to access the data here: https://adni.loni.usc.edu/data-samples/access-data/.

Best of luck!
